// apps/syn-landing/src/components/SMark.tsx
import { useEffect } from "react";
import { sMark, S_MARK_FACES } from "@syn137/skyline-core/geometry";

/** The brand S in cubes, same geometry and faces as Skyline's SMark pattern. */
const MARK = sMark(40);

let elementModule: Promise<unknown> | null = null;

/**
 * Registers <sky-s-mark> once, after first paint: the element pulls in the
 * shared Svelte runtime chunk, which nothing needs for the first render.
 */
function loadElement(): void {
  if (elementModule) return;
  const load = () => {
    elementModule ??= import("@syn137/skyline-svelte-v5/elements/s-mark");
  };
  if ("requestIdleCallback" in window) window.requestIdleCallback(load);
  else setTimeout(load, 1);
}

interface SMarkProps {
  /** Width in px; the height follows the mark's aspect ratio. */
  size: number;
  /** Accessible name; "" makes the mark decorative (next to the wordmark). */
  label?: string;
}

/**
 * <sky-s-mark> with a static light-DOM fallback: the same SVG, drawn from
 * skyline-core's sMark() with token fills, so the S shows before (and
 * without) the element's script. The upgraded element renders into its
 * shadow root and the fallback is no longer shown.
 */
export default function SMark({ size, label = "Syntropic137" }: SMarkProps) {
  useEffect(loadElement, []);
  const decorative = label === "";
  return (
    <sky-s-mark className="s-mark" size={size} label={label} style={{ width: size }}>
      <svg
        className="s-mark__fallback"
        viewBox={MARK.viewBox}
        width={size}
        role={decorative ? undefined : "img"}
        aria-label={decorative ? undefined : label}
        aria-hidden={decorative ? true : undefined}
        focusable="false"
      >
        {MARK.cubes.map((c) => {
          const f = S_MARK_FACES[c.tone];
          return (
            <g key={c.order} style={{ stroke: f.stroke ?? undefined }}>
              <polygon points={c.left} style={{ fill: f.left }} />
              <polygon points={c.right} style={{ fill: f.right }} />
              <polygon points={c.top} style={{ fill: f.top }} />
            </g>
          );
        })}
      </svg>
    </sky-s-mark>
  );
}

// packages/syn-ui/skyline-svelte-v5/src/patterns/SMark/SMark.svelte
<!--
  S Mark (Landing nav, hero and footer; the app's top bar later): the
  Syntropic137 S as eleven isometric cubes, from skyline-core's sMark().
  Faces are tokens (S_MARK_FACES), so the blue cubes follow the accent.
  `animate` drops the cubes in one by one with motion.css's sky-sdrop; the
  static mark is the end state (reduced motion, no motion.css, no script).
-->
<script lang="ts">
  import { sMark, sMarkDelay, S_MARK_FACES } from '@syn137/skyline-core/geometry'
  import type { SMarkProps } from './types'

  let { size, animate = false, label = 'Syntropic137', ...rest }: SMarkProps = $props()

  const mark = sMark(40)
  // A bare number, or a numeric string from an HTML attribute, is pixels.
  const width = $derived(typeof size === 'number' || (typeof size === 'string' && /^\d+(\.\d+)?$/.test(size)) ? `${size}px` : size)
</script>

<svg
  {...rest}
  class="sky-s-mark"
  viewBox={mark.viewBox}
  style:width
  role={label ? 'img' : undefined}
  aria-label={label || undefined}
  aria-hidden={label ? undefined : 'true'}
  focusable="false"
>
  {#each mark.cubes as c (c.order)}
    {@const f = S_MARK_FACES[c.tone]}
    <g class={animate ? 'sky-sdrop' : undefined} style:animation-delay={animate ? `${sMarkDelay(c.order)}s` : undefined} style:stroke={f.stroke}>
      <polygon points={c.left} style:fill={f.left} />
      <polygon points={c.right} style:fill={f.right} />
      <polygon points={c.top} style:fill={f.top} />
    </g>
  {/each}
</svg>

<style>
  .sky-s-mark {
    display: block;
    width: 100%;
    height: auto;
    overflow: visible;
  }
  .sky-s-mark g {
    stroke-width: 1;
    stroke-linejoin: round;
  }
</style>
